; this ini has the same rules as launch.ini and must be placed on the root of a device
; paths are determined the same way (Usb/Hdd/etc) see dash launch sample ini for more info

; title ID is used for ini category (can be found in fsd, with xextool, the folder name built by iso2god/nxe install)
; use only numbers and small letters here
; only disks listed in the correct titleid category will be parsed from this ini
[454108df]
; dead space 2
; paths for extracted games MUST end in a \
; extracted game folder MUST have a default.xex in it, even if it's just a 0 byte file
disk1 = Hdd:\Games\Dead Space 2 D1\
; paths for GOD games must point at the root CON descriptor, and NOT end in a \
disk2 = Hdd:\Content\0000000000000000\454108DF\00007000\B8605B3BAFB748ACD08A

