; dead space 2
; title ID for category, can be found in fsd, with xextool, the folder name built by iso2god/nxe install
[454108df]
; paths for extracted game folders MUST end in a \
; this folder MUST have a default.xex in it
disk1 = Hdd:\Games\Dead Space 2 D1\
; paths for GOD games must point at the root CON descriptor, and NOT end in a \
disk2 = Hdd:\Content\0000000000000000\454108DF\00007000\B8605B3BAFB748ACD08A

;disk1 = Hdd:\Content\0000000000000000\454108DF\00007000\831BBD71B701B42512FF
