#ifndef __OPTS_H
#define __OPTS_H

#include "../_common.h"

// option bitfields
#define OPT_NONE				0
#define OPT_NXEMINI				0x00000001 // if 1 nxemini miniblade exits in dash are hooked (modifiable)
// #define OPT_CONTPATCH			0x00000002 // if 1 LIVE containers will be patched on loads (status)
//#define OPT_REGION				0x00000004 // if 1 ability to override region by LB is enabled (status)
#define OPT_DVDEXIT				0x00000008 // if 1 ejecting dvd video will return to official dash (modifiable)
#define OPT_XBLAEXIT			0x00000010 // if 1 quitting a xbla will return to official dash (modifiable)
#define OPT_SOCKPATCH			0x00000020 // if 1 all titles have privs modified for insecure sockets (modifiable)
#define OPT_NOSYSEXIT			0x00000040 // if 1 using miniblades to get to system settings will not work (modifiable)
#define OPT_PASS_LAUNCHD		0x00000080 // if 1 launch data will be passed as-is to the next application (modifiable) 
#define OPT_FATAL_FREEZE		0x00000100 // if 1 dash launch will not try to catch fatal exceptions (status)
#define OPT_FATAL_REBOOT		0x00000200 // if 1 dash launch will try to reboot on fatal exceptions (modifiable/status, depends on NOFREEZE at boot time)
#define OPT_PING_PATCH			0x00000400 // if 1 ping limit has been patched in xam (status)
#define OPT_SAFE_REBOOT			0x00000800 // if 1 changes reboot method to hard reboot for jtag that can't soft reboot (modifiable/status, depends on NOFREEZE at boot time and)
#define OPT_SHOW_FAREN			0x00001000 // if 1 temps will be displayed in Fahrenheit
// #define OPT_EXCEPT_HANDLE		0x00001000 // if 1 dash launch has hooked the kernel exception handler (status)
#define OPT_DEBUG_OUTPUT		0x00002000 // if 1 dash launch will output dbgprint to UART (status, depends on EXCEPT HANDLE being 1)
// #define OPT_UPDATE_BLOCK		0x00004000 // if 1 dash launch is blocking updaters by one-time patching xam strings (status)
#define OPT_LIVE_BLOCK			0x00008000 // if 1 xbox is prevented from resolving known live servers (modifiable)
// #define OPT_HUD_DISABLE			0x00010000 // if 1 xbox is preventing HUD miniblades from coming up (status)
#define OPT_XHTTP_PATCHED		0x00020000 // if 1 xam is patched to allow XHTTP to work w/o signing in (status)
#define OPT_SIGN_NOTICE_DISABLE	0x00040000 // if 1 dash launch is dispatching single button warnings generated by singin.xex (status)
#define OPT_SELECT_SHUTDOWN		0x00080000 // if 1 holding guide button will autoselect shutdown console item (modifiable)
#define OPT_FORCE_SHUTDOWN		0x00100000 // if 1 holding guide button will shut down console (modifiable)
// #define OPT_BCAST_TEMPS			0x00200000 // if 1 then a task is broadcasting temps and the tempdata export is getting updated (status)
// #define OPT_HDALIVE				0x00400000 // if 1 then a task is trying to keep usb hdd from spinning down (status)
#define OPT_AUTOFAKE			0x00400000 // starting indie games will enable/disable fakelive automatically
#define OPT_FAKELIVE			0x00800000 // if 1 then fakelive is enabled (status)
#define OPT_LIVE_STRONG			0x01000000 // if 1 AND liveblock is enabled, strong filter list is used
// #define OPT_HIDE_NETSTORE		0x02000000 // if 1 network storage should never show up in a title
#define OPT_SHUTDOWN_SHOWTEMP	0x04000000 // if 1 temps are shown on the shutdown dialog
#define OPT_AUTO_CONT_FAKE		0x08000000 // if 1 contPatch is enabled for specific content
#define OPT_CONT_PATCH			0x10000000 // if 1 contPatch is enabled
#define OPT_LIC_PATCH			0x20000000 // if 1 license bit masks are patched
#define OPT_XBLA_PATCH			0x40000000 // if 1 xbla license bits are patched

#define AUT_BOOT_REP	30

typedef void (*DLOPTHANDLER)(PDWORD val); // opt is PDL_OPTS_INFO

typedef struct _DL_OPTS_INFO {
	char* optName;
	DL_OPT_TYPES optType;
	DWORD defVal;
	DWORD optMask;
	DLOPTHANDLER optHandler; // !! do not call this directly, internal use only !!
	DWORD optCategory;
} DL_OPTS_INFO, *PDL_OPTS_INFO;

BOOL getOpt(DWORD omask);
void setOpt(DWORD omask);
void unSetOpt(DWORD omask);
void initOpts(void);
void setOptsFromIni(void);

BOOL dlaunchGetOptValByName(char* optName, PDWORD val);
BOOL dlaunchSetOptValByName(char* optName, PDWORD val);

void enableFakeLive(BOOL isXna);
void disableFakeLive(void);
BOOL procTitleFakeLive(DWORD tid);

#endif // __OPTS_H
